development:
  api_key: 522baec079439455ab358362125a603f
  secret_key: c68e2cb86e9c7866633957ca96b09605
  conavas_page_name: http://aritbooker.turetzky.org
  callback_url: http://aritbooker.turetzky.org
test:
  api_key: 522baec079439455ab358362125a603f
  secret_key: c68e2cb86e9c7866633957ca96b09605
  conavas_page_name: http://aritbooker.turetzky.org
  callback_url: http://aritbooker.turetzky.org
production:
  api_key: 522baec079439455ab358362125a603f
  secret_key: c68e2cb86e9c7866633957ca96b09605
  conavas_page_name: http://aritbooker.turetzky.org
  callback_url: http://aritbooker.turetzky.org